# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\aWork\coding\qgis-plugs-dev\concaveman_qgis\concaveman_qgis_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConcavemanQGISDialogBase(object):
    def setupUi(self, ConcavemanQGISDialogBase):
        ConcavemanQGISDialogBase.setObjectName("ConcavemanQGISDialogBase")
        ConcavemanQGISDialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(ConcavemanQGISDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.cbVectors = QtWidgets.QComboBox(ConcavemanQGISDialogBase)
        self.cbVectors.setGeometry(QtCore.QRect(90, 40, 261, 20))
        self.cbVectors.setObjectName("cbVectors")
        self.tbVectors = QtWidgets.QToolButton(ConcavemanQGISDialogBase)
        self.tbVectors.setGeometry(QtCore.QRect(360, 40, 25, 19))
        self.tbVectors.setObjectName("tbVectors")
        self.label = QtWidgets.QLabel(ConcavemanQGISDialogBase)
        self.label.setGeometry(QtCore.QRect(7, 41, 61, 16))
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(ConcavemanQGISDialogBase)
        self.widget.setGeometry(QtCore.QRect(160, 100, 220, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.dsbLenThres = QtWidgets.QDoubleSpinBox(self.widget)
        self.dsbLenThres.setDecimals(3)
        self.dsbLenThres.setObjectName("dsbLenThres")
        self.horizontalLayout.addWidget(self.dsbLenThres)
        self.widget1 = QtWidgets.QWidget(ConcavemanQGISDialogBase)
        self.widget1.setGeometry(QtCore.QRect(10, 100, 109, 22))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.dsbConcavity = QtWidgets.QDoubleSpinBox(self.widget1)
        self.dsbConcavity.setObjectName("dsbConcavity")
        self.horizontalLayout_2.addWidget(self.dsbConcavity)

        self.retranslateUi(ConcavemanQGISDialogBase)
        self.button_box.accepted.connect(ConcavemanQGISDialogBase.accept)
        self.button_box.rejected.connect(ConcavemanQGISDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(ConcavemanQGISDialogBase)

    def retranslateUi(self, ConcavemanQGISDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ConcavemanQGISDialogBase.setWindowTitle(_translate("ConcavemanQGISDialogBase", "Concaveman QGIS"))
        self.tbVectors.setText(_translate("ConcavemanQGISDialogBase", "..."))
        self.label.setText(_translate("ConcavemanQGISDialogBase", "Load Vector:"))
        self.label_3.setText(_translate("ConcavemanQGISDialogBase", "Length threshold:"))
        self.label_2.setText(_translate("ConcavemanQGISDialogBase", "Concavity:"))
